### ISSUE TITLE
sj:menu behaves differently with a list or map than it does with specified sj:menuItem tags

### ISSUE THREAD

**Issue by sdutry** [struts-community-plugins/struts2-jquery#106]
- When you specify the `sj:menuItem` tags, the whole item is clickable.
- When you specifiy a list or map (as attribute `list`) only the text is clickable.

The difference is the following:
- When you define the `sj:menuItem` tags, what gets bound is the `li` tag
- Otherwise, it's only the `a` tag around the text (inside a `div` inside the `li`) that gets bound

This is visible in the [struts2-jquery-showcase](http://struts.jgeppert.com/struts2-jquery-showcase/index.action)

#### menuItem

```
jQuery(document).ready(function () {
    var options_menuItem_1827255159 = {};
    options_menuItem_1827255159.jqueryaction = "menuItem";
    options_menuItem_1827255159.id = "menuItem_1827255159";
    options_menuItem_1827255159.targets = "result";
    options_menuItem_1827255159.href = "/struts2-jquery-showcase/ajax2.action";
    options_menuItem_1827255159.effect = "highlight";
    options_menuItem_1827255159.effectduration = 2500;
    options_menuItem_1827255159.effectoptions = {};

    jQuery.struts2_jquery_ui.bind(jQuery('#menuItem_1827255159'),options_menuItem_1827255159);

});
```
where `menuItem_1827255159` is the `li` tag
#### list
```
jQuery(document).ready(function () {
    var options_menuStringList_li_anchor_2 = {};
    options_menuStringList_li_anchor_2.jqueryaction = "menuItem";
    options_menuStringList_li_anchor_2.id = "menuStringList_li_2_anchor";
    options_menuStringList_li_anchor_2.targets = "result";
    options_menuStringList_li_anchor_2.href = "/struts2-jquery-showcase/echo.action";
    options_menuStringList_li_anchor_2.hrefparameter = "echo=JavaScript";

    jQuery.struts2_jquery_ui.bind(jQuery('#menuStringList_li_2_anchor'),options_menuStringList_li_anchor_2);
 });
```
where `menuStringList_li_2_anchor` is the `a` tag inside the `div` inside the `li` tag

Personaly, i think it would be better if they reacted the same. 
(with my preference to the way menuItem works since that whole area lights up)

@jogep What do you think about this?

**Comment by jogep** [comment]
@sdutry you are right they should have the same behavior. I will check this.

**Comment by jogep** [comment]
Close issue because version 4.0.3 is released.
