### ISSUE TITLE
NPE on using tags which extend AbstractContainerTag

### ISSUE THREAD

**Issue by aleksandr-m** [struts-community-plugins/struts2-jquery#110]
Using simple `<sj:div>` results in NPE being thrown. It happens because of this kind of [`if`-s](https://github.com/struts-community-plugins/struts2-jquery/blob/release/4.0.3/struts2-jquery-plugin/src/main/java/com/jgeppert/struts2/jquery/components/AbstractContainer.java#L210) in the `AbstractContainer` `evaluateExtraParams` method.

Null check is needed before calling `findString` or maybe `resizable`, `droppable`, etc. should be initialized with default values in `AbstractContainerTag`.

**Comment by sdutry** [comment]
@aleksandr-m 
Is it correct in assuming that this is just for the following statements?  
other `findString` calls seem to be surrounded with null-checks
* `resizable` (line `210`)
* `droppable` (line `298`)
* `draggable` (line `348`)
* `selectable` (line `481`)
* `sortable` (line `522`)

Also,

When are you getting this exactly?
There's currently a test that tests the `sj:div` tag:
* [ajax-div.jsp](https://github.com/struts-community-plugins/struts2-jquery/blob/release/4.0.3/struts2-jquery-integration-tests/src/main/webapp/WEB-INF/content/includes/div/ajax-div.jsp)
* [DivTagIT.java](https://github.com/struts-community-plugins/struts2-jquery/blob/release/4.0.3/struts2-jquery-integration-tests/src/test/java/com/jgeppert/jquery/div/DivTagIT.java)

If we have the exact situation, I could add a test for it.

**Comment by aleksandr-m** [comment]
Yes, seems like that. What do you think about providing defaults for `resizable` and such?

**Comment by sdutry** [comment]
@aleksandr-m 
can you please provide an example for this issue.

I seem unable to replicate this.
Also, what version are you using for the following?
* `struts2-jquery`
* `struts2`

**Comment by aleksandr-m** [comment]
Turns out that it was a bug in the Struts2, which is fixed in this [commit](https://github.com/apache/struts/commit/7dbe3ea8bb97cd004e77541c761bbe20e4373c3d#diff-49e25ce689738bd6bdcedb2962389069).

If upgrade is not an option then simple workaround is to set all aforementioned attributes to `false` in JSP.
