### ISSUE TITLE
add convenience methods to TreeNode to make it easier to use

### ISSUE THREAD

**Issue by sdutry** [struts-community-plugins/struts2-jquery#115]
module:
- `struts2-jquery-tree-plugin`

class:
- `com.jgeppert.struts2.jquery.tree.result.TreeNode`

#### Add a method addChild
Currently `TreeNode` only has a getChildren and a setChildren method, making it so that, when you want to add a childnode, you have to get the collection and then add it to the collection.

Seeing that the collection gets initialized to an empty TreeSet by default, this should be

    public boolean addChild(final TreeNode treeNode) {
        return childrens.add(treeNode);
    }
#### Add a method addChildren
Similar to addChild, but now for a collection of TreeNode objects instead of a single one.

    public boolean addChildren(final Collection<TreeNode> treeNodes) {
        return childrens.addAll(treeNodes);
    }

**Comment by jogep** [comment]
Close issue because version 4.0.3 is released.
