### ISSUE TITLE
Struts2 Version

### ISSUE THREAD

**Issue by aeonoftime** [struts-community-plugins/struts2-jquery#119]
It is not clear which version of Struts2jquery is compatible with what version of Struts2? Could this be clearly outlined in the Readme file?

**Comment by sdutry** [comment]
You are correct.
It could be clearer.

Currently the only thing saying anything about it is:

> Latest version which is compatible to Struts 2.3.x is version [3.7.1].

Do you have any suggestions as to where and how to display the versions.

**Comment by aeonoftime** [comment]
This sentence is unclear. Perhaps some sort of reference of current and the most recent versions.

ie Struts2-JQuery Version 4.0.3 has a minimum requirement of Struts 2.3.x and recommended Struts2 version of 2.5.8.  I have only thrown in numbers here as I don't know the answer.

**Comment by sdutry** [comment]
Ok, i'll see what i can do.

**Comment by sdutry** [comment]
@aeonoftime 
Can you please check this [branch](https://github.com/sdutry/struts2-jquery/tree/issue119) to see if this would be an acceptable improvement?

If you have better or different ideas on this, i'm open for suggestions.

**Comment by aeonoftime** [comment]
I think that is much more clear.
