### ISSUE TITLE
update wiki changelog for versions 4.x.x

### ISSUE THREAD

**Issue by sdutry** [struts-community-plugins/struts2-jquery#121]
Wiki changelog page needs to be updated to hold info about the 4.x.x versions

page:
[Changelog](https://github.com/struts-community-plugins/struts2-jquery/wiki/Changelog)

* missing info about existing versions:
  * `4.0.1`
  * `4.0.2`
* version present on page that, to my knowledge, doesn't exist:
  * `4.0.0`

**Comment by sdutry** [comment]
Added changes for version `4.0.2`

@jogep 
Could you please complete the remaining sections when you find the time.  
Sections:
  * `4.0.1`
  * `4.0.0`
(I think you're better suited to list the changes and bugfixes for these versions as i only joined late during the process of these versions)

Also, feel free to check and adjust the change i made.

**Comment by flofourcade** [comment]
Updated the changelog with what I remember having done for 4.0.1 milestone.

I'll try to find some time to write a wiki on the datatables plugin, and to update jstree but I think I'll need someone to correct me, cause it's quite likely that I'll make a lot of grammatical, syntaxical mistakes (you guess it, I'm not a native English speaker  :-)  )

**Comment by sdutry** [comment]
Don't worry, i'm not a native English speaker either. Most important thing is the info being present. (Also autocorrect is annoying)

**Comment by jogep** [comment]
Version 4.0.0 was never officially released. I will update some information for the 4.0.1 section.

**Comment by jogep** [comment]
I added some informations about version and compatibility changes.

**Comment by flofourcade** [comment]
Hi @jogep @sdutry. 

I started to write a wiki about the datatables plugin. For now it's an introduction, feature list and tag attributes reference. Soon I'll add other pages to explain more in detail how the showcase examples work, and other thing like theming, ...

While we're talking about DataTables, I'm planning to add some new features like a built in editor. Official DataTables Editor is a commercial plugin, so I'll try to implement a custom open source solution in our struts 2 datatables plugin, which can take advantage of other plugins (topic system, widgets, bootstrap plugin).

In an other subject I was thinking on how we could improve handling of JSON result, and I thought we could use some JS templating engine (by eg Handlebar JS,...) to transform JSON into HTML and inject it into some target containers. It could be easy with the topic system. A typical use case could be click on a 
`<sj:a />` -> JSON response in success topic -> execution of a JS template -> injection into target ->other action (by eg opening of a modal).

Please tell me your opinion on all of these ideas, and I'l start to work on it ASAP.
