### ISSUE TITLE
upgrade to latest struts2

### ISSUE THREAD

**Issue by sdutry** [struts-community-plugins/struts2-jquery#122]
* new struts2 version: `2.5.10`
* [version notes](http://struts.apache.org/docs/version-notes-2510.html)
* shouldn't require any changes to the code of the `struts2-jquery` project (other than `pom.xml`-files)

**Comment by sdutry** [comment]
upgrade to struts `2.5.10.1`

**Comment by sdutry** [comment]
upgrade to struts `2.5.12`

**Comment by sdutry** [comment]
upgrade to struts `2.5.13`

**Comment by aleksandr-m** [comment]
It's been a while since the last release. Maybe we should release `4.0.3`? Or is there any specific issue that needs to be done before?

Also, have anyone tried to update jQuery to 3.x?

@jogep @sdutry

**Comment by sdutry** [comment]
@aleksandr-m 
i'd love to see pull #138 merged which should fix #46 ,  #36 and #140 

I tried making a project for the `4.0.3` release a little while ago see: [Release 4.0.3](https://github.com/struts-community-plugins/struts2-jquery/projects/1)

**Comment by jogep** [comment]
Close issue because version 4.0.3 is released.
