### ISSUE TITLE
Remove log4j 1.2.17 dependency

### ISSUE THREAD

**Issue by aleksandr-m** [struts-community-plugins/struts2-jquery#125]
@jogep @sdutry 
1) In which branch should it go? `release/4.0.3`?
2) Should PR be created or direct commit is ok?
3) Is running `mvn clean install` is enough to fully build and test project?

**Comment by sdutry** [comment]
@aleksandr-m 
#### In which branch should it go? release/4.0.3?
`release/4.0.3` is the current active branch that's in development
#### Should PR be created or direct commit is ok?
If you're sure of your changes and they're small enough, then a PR is not realy required in my opinion.
However, if you do make a PR, then [Travis-CI](https://travis-ci.org/struts-community-plugins/struts2-jquery) will start a build that runs the existing tests on the PR-code. (there will be a check visible on the PR in github)
A [Travis-CI](https://travis-ci.org/struts-community-plugins/struts2-jquery) build takes place for any commit to any branch, not just for pull requests.
#### Is running mvn clean install is enough to fully build and test project?
* Yes in the sense that
  * The `verify` phase is run when using `install`
  * It will run the existing integration tests that use the `HtmlUnitDriver`.
* No in the sense that: 
  * It will not run the existing integration tests that use the `PhantomJSDriver`
  * Not everything is covered with the current tests
* Creating a pull request automaticaly builds and tests the project with both the `HtmlUnitDriver` and the `PhantomJSDriver` config
* For more information on how to run the tests or specific ones, there is a [README.md](https://github.com/struts-community-plugins/struts2-jquery/blob/release/4.0.3/struts2-jquery-integration-tests/README.md) file present in the `struts2-jquery-integration-tests` module.

If you have further questions, feel free to ask.
Also, should you have suggestions for improving the test-setup, don't hesitate. (the test-setup is still in progress, see #90 )

**Comment by aleksandr-m** [comment]
off-topic: Any reason `target` folder isn't listed in `.gitignore`?

**Comment by sdutry** [comment]
@aleksandr-m 
The reason definately is: because i forgot to add it to the `.gitignore` file

**Comment by sdutry** [comment]
#126
