### ISSUE TITLE
add target folder and IDE specific files to .gitignore file

### ISSUE THREAD

**Issue by sdutry** [struts-community-plugins/struts2-jquery#127]
as mentioned in #125 , not all target folders are ignored

**Comment by aleksandr-m** [comment]
It would be great to add IDE specific folders as well.
E.g.
```
.classpath
.project
.settings/
.idea/
```

**Comment by sdutry** [comment]
@aleksandr-m updated issuetitle

**Comment by jogep** [comment]
Close issue because version 4.0.3 is released.
