### ISSUE TITLE
update selenium and htmlunit to latest version

### ISSUE THREAD

**Issue by sdutry** [struts-community-plugins/struts2-jquery#130]
### module
* `struts2-jquery-integration-tests`

| groupId | artifactId | version  |
| -- | --| --|
| `org.seleniumhq.selenium` | `selenium-server` | `3.2.0` |
| `org.seleniumhq.selenium` | `htmlunit-driver` | `2.25` |

**Comment by sdutry** [comment]
newer version are available

| groupId | artifactId | version  |
| -- | --| --|
| `org.seleniumhq.selenium` | `selenium-server` | `3.5.2` |
| `org.seleniumhq.selenium` | `htmlunit-driver` | `2.27` |

Also needs a managed version of guava since it now suddenly fails the build because of missing method

**Comment by sdutry** [comment]
with the newest versions, the tests using multiple alerts no longer work.

**Comment by jogep** [comment]
Close issue because version 4.0.3 is released.
