### ISSUE TITLE
Missing required js when using <sj:select /> with autocomplete="true" 

### ISSUE THREAD

**Issue by flofourcade** [struts-community-plugins/struts2-jquery#140]
Due to js not being imported, it's impossible to use <sj:select /> with autocomplete="true" .
JS are tooltip.js and uniqueId.js and safe-active-element.

The showcase example works because missing js are imported by other tags.

**Comment by flofourcade** [comment]
PR #138

**Comment by jogep** [comment]
Close issue because version 4.0.3 is released.
