### ISSUE TITLE
struts2 jquery grid plugin cause javascript error when grid data is not loaded

### ISSUE THREAD

**Issue by afattahi54** [struts-community-plugins/struts2-jquery#148]
We are using struts2 jquery plugin 4.0.2.
We use sjg:grid to load data from an action. 

```java
<sjg:grid gridModel="gridModel" action="\data-provider.action"....
```

The action is

```java
@Action(value = "data-provider", results = 
       { @Result(type = "json",params = { "root", "action" }) })
dataProvider(){

try{
    List<Model> = doBusiness();
    setGridModel(List<Model>);
    return SUCCESS; 

}catch{
   HttpServletResponse response = this.getServletResponse();
   response.setContentType("application/json");
   response.getWriter().write("{ \"errors\":\"false\"}");
   return SUCCESS; 
}

}
```

Also some javascript to handle error cases:
```javascript
$(document).ajaxComplete(function(event, xhr, settings) {
   var response = jQuery.parseJSON(xhr.responseText);
     if (response.errors) {
       alert("Could not load grid");
     }

}) 
```

It works fine whether the grid loads or not.

How ever when I set the sortableRows="true" things change!!

When there is no exception in action and grid data is loaded things are working. However when there is exception and we write our custom json ( {"error","true"} ), JavaScript exception happens.

The error is :

````java
Uncaught TypeError: Cannot set property 'beforeStop' of undefined
    at HTMLTableElement.params.gridComplete (eval at globalEval (jquery-2.2.4.js:343), <anonymous>:331:22)
    at HTMLTableElement.updatepager (eval at globalEval (jquery-2.2.4.js:343), <anonymous>:2301:59)
    at addJSONData (eval at globalEval (jquery-2.2.4.js:343), <anonymous>:1985:20)
    at Object.success (eval at globalEval (jquery-2.2.4.js:343), <anonymous>:2387:15)
    at fire (jquery-2.2.4.js:3187)
    at Object.fireWith [as resolveWith] (jquery-2.2.4.js:3317)
    at done (jquery-2.2.4.js:8757)
    at XMLHttpRequest.<anonymous> (jquery-2.2.4.js:9123)
````

I find the error is in jquery.grid.struts2.js here is the code partition which seems to make error:

````javascript
if (o.sortableRows) {
        self.log('sortable rows for : ' + o.id);

        if (!soo) {
            soo = eval("( " + soos + " )");
        } else {
            soo = {};
        }
        soo.beforeStop = self.pubTops($elem, o.onalw, o.sortableonbeforestoptopics);
        soo.stop = self.pubTops($elem, o.onalw, o.sortableonstoptopics);
        soo.start = self.pubTops($elem, o.onalw, o.sortableonstarttopics);
        soo.sort = self.pubTops($elem, o.onalw, o.sortableonsorttopics);
        soo.activate = self.pubTops($elem, o.onalw, o.sortableonactivatetopics);
````

It was ok in struts2 jquery plugin 3.7.1

any comments

**Comment by sdutry** [comment]
Am i summarizing the problem correctly?

- `sjg:grid` tag has attribute `sortableRows="true"`
- The remote action providing the data throws an Exception
- Resulting in a javascript error

I'll see if i can reproduce this tomorrow.

**Comment by afattahi54** [comment]
Yes I face another similar issue to.

Just create a grid  which has an href set ( the dataType should not be local)  and set the sortableRows="true" you will face JavaScript error. 

To fix it I removed sortableRows="true"  and added below

````
$("#gridtable").subscribe('grid_compelete', function(event, data) {
    		$("#gridtable").jqGrid('sortableRows');
})
````

**Comment by sdutry** [comment]
Created project for reproducing the problem
* [https://github.com/sdutry/struts2-jquery-issue-148](https://github.com/sdutry/struts2-jquery-issue-148)

Still have some steps to take in order to reproduce the problem.

In the meantime i think i'm starting to understand what the problem is.

can you try one of the following fixes?

* change the error-handling json object to 
```java
response.getWriter().write("{ \"errors\":false, \"gridModel\":[]}");
```
* **or even better yet**
  * add a boolean errors to you JSON-result action and default it on false
  * in the catch of the exception:
    * set the errors boolean to true
    * set the gridModel to an empty List
```java
private boolean errors = false;
...
}catch(final Exception e){
   log.error("Error while fetching grid data", e);
   setGridModel(Collections.<Model>emptyList());
   errors = true;
   return SUCCESS;
}
```

I don't think there's any reason to directly write a JSON object to the response writer

**Comment by sdutry** [comment]
Regardless of my previous comment, there does seem to be a problem with the sortableRows attribute

**Comment by sdutry** [comment]
@afattahi54 
Created a [branch](https://github.com/sdutry/struts2-jquery/tree/issue148) to fix it.
Can you check if this fixes your problem.

Steps:
- checkout the branch
```
git clone https://github.com/sdutry/struts2-jquery.git
cd struts2-jquery
git checkout -b issue148 origin/issue148
```
- run `mvn install` to install it localy
```
mvn install -DskipTests=true -Dmaven.javadoc.skip=true
```
- use version 4.0.3-SNAPSHOT of the localy installed `struts2-jquery-plugin` and `struts2-jquery-grid-plugin` in your project
```xml
    <struts2-jquery.version>4.0.3-SNAPSHOT</struts2-jquery.version>
```
- check if the problem still exists

Please let me know if this fixes the problem. 
- If it does i'll merge it into the `release/4.0.3` branch
- If it doesn't, also let us know.

**Comment by afattahi54** [comment]
Dear @sdutry wow! I was on vacation and could not follow this issue. Now I see you have worked on it a lot ! 
Thanks for your help! 

I have tested and the fix worked 👍 

When will the 4.0.3 released !

**Comment by jogep** [comment]
Close issue because version 4.0.3 is released.
