### ISSUE TITLE
Switch to jQuery 3.x.x version

### ISSUE THREAD

**Issue by jogep** [struts-community-plugins/struts2-jquery#154]

**Comment by sdutry** [comment]
What's the status on this issue?

Is there any way i can help with this?

**Comment by jogep** [comment]
Thanks for offering help on this issue. I hope I can focus on it in the near future and provide an update on this.

**Comment by marwin1991** [comment]
Hello, is there any progress ? 
I have been using this plugin with 3.3.1 sttruts and everything was working correctly, but after migrating to 3.6.0 datepicker stoped working

**Comment by marwin1991** [comment]
After migrating to 3.6.0 of jquery I had a problem with mimification, so it can be alos here a good idea to start sovling problems.

**Comment by sdutry** [comment]
will be part of the 5.0.0 release with update jQuery, jQuery ui and struts version

see: #210
