### ISSUE TITLE
Showcase

### ISSUE THREAD

**Issue by mohdrzu** [struts-community-plugins/struts2-jquery#164]
Hi, I am currently implement this plugin for my project. I got 502 error when trying to access the showcase website. Is the website has been moved?

**Comment by sdutry** [comment]
@r-zulman 
You are correct. The showcase seems to be down.
I'll see if i can contact the owner.

Workaround to have the showcase available:

1. clone the struts2-jquery repository
2. switch to tag 4.0.3
3. move to folder `struts2-jquery-showcase`
4. run the application on a jetty server: `mvn jetty:run`

**Comment by jogep** [comment]
Hi I restarted the showcase and it is running again. But like @sdutry already mentioned you always can run the showcase in your local dev environment.

Thank you for informing us about the outage.
