### ISSUE TITLE
Timeframe for use of jQuery 3.3.1

### ISSUE THREAD

**Issue by nazario1** [struts-community-plugins/struts2-jquery#172]
When will struts2-jquery start using the latest jQuery 3.3.1. Currently, the <sj:head tag generates the following, which means it's using jQuery version 2.2.4;

<script type="text/javascript" src="/nepedia/struts/js/base/jquery-2.2.4.js"></script>
<script type="text/javascript" src="/nepedia/struts/js/base/jquery-ui.js?s2j=4.0.3"></script>
<script type="text/javascript" src="/nepedia/struts/js/plugins/jquery.form.js?s2j=4.0.3"></script>
<script type="text/javascript" src="/nepedia/struts/js/plugins/jquery.subscribe.js?s2j=4.0.3"></script>

Thanks,
Oscar Nazario
LLNL

**Comment by sdutry** [comment]
upcoming version 5.0.0 will work with jQuery 3.6.0

see : #210
