### ISSUE TITLE
How often are the issues placed here looked at?

### ISSUE THREAD

**Issue by nazario1** [struts-community-plugins/struts2-jquery#175]
I posted two questions back in March and there has been no response yet. Please advise.
Thanks,
Oscar

**Comment by jnhelal** [comment]
Same for me !

**Comment by lukaszlenart** [comment]
I think it would be better to ask on [the Struts User mailing list](https://lists.apache.org/list.html?user@struts.apache.org) instead. This isn't an officially supported plugin by the Struts team but there is a few people involved in the plugin development.

**Comment by nazario1** [comment]
Lukasz,
THANK YOU VERY MUCH!!! We have been unable to upgrade from 3.7.1 to 4.0.3 due to this issue. The treegrid libraries are not included. Here is my initial post back on March 2019 https://github.com/struts-community-plugins/struts2-jquery/issues/171
Oscar

**Comment by sdutry** [comment]
Although issues here were not looked at often, development recently got picked back up.

The main focus of the development atm is focused on the following:

- compatibility with struts version 6.0.0
- update of jquery library to version 3.6.0
- update of jquery-ui to version 1.13.1

Once this release finaly happens, the other issues will be picked up again, most likely only for the new version of the plugin (meaning for struts 6.0.0 and jquery 3.6 and jquery-ui 1.13.1)

will close this issue for now.
