### ISSUE TITLE
Download Snapshot from maven

### ISSUE THREAD

**Issue by afattahi54** [struts-community-plugins/struts2-jquery#19]
I tried to download the snapshot from maven.
I found the the repository is at sonatype. I set the repository as below and set struts 2 jquery plugin version to 4.0.0-SNAPSHOT.
```xml
  <repositories>
      <repository>
          <id>oss-sonatype</id>
          <name>oss-sonatype</name>
        <url>https://oss.sonatype.org/content/repositories/snapshots/</url>
        <snapshots>
            <enabled>true</enabled>
        </snapshots>
    </repository>
</repositories>
```
But the maven could not get it. Any comments ?!

**Comment by jogep** [comment]
I use it like this:

    <repositories>
        <repository>
            <id>sonatype.oss.snapshots</id>
            <name>Sonatype OSS Snapshot Repository</name>
            <url>http://oss.sonatype.org/content/repositories/snapshots</url>
        </repository>
    </repositories>

May it is the leading "/" in the url?
