### ISSUE TITLE
Old jQuery Libary 2.2.4 has security issues so need to upgrade to jQuery 3.5.0+ preferably jQuery 3.6.0

### ISSUE THREAD

**Issue by lalumastan** [struts-community-plugins/struts2-jquery#194]
**Title**
During a recent Acunetix Security Audit, the scanner flagged "jquery 2.2.4" as a vulnerable JavaScript library.  So the jQuery library needs to be upgraded to jQuery 3.5.0+ preferably jQuery 3.6.0.  Please find the details below:

**Description**
You are using one or more vulnerable JavaScript libraries. One or more vulnerabilities were reported for this version of the library. Consult Attack details and Web References for more information about the affected library and the vulnerabilities that were reported. Impact Consult References for more information.

**Recommendation**
Upgrade to the latest version.

**Details**
jquery 2.2.4

**Detection method**
The library's name and version were determined based on the file's name, and contents.
Acunetix verified the library version and the associated vulnerabilities with the file's unique syntax fingerprint,
which matched the syntax fingerprint expected by Acunetix.

**References**
https://github.com/jquery/jquery/issues/2432
https://blog.jquery.com/2020/04/10/jquery-3-5-0-released/
https://mksben.l0.cm/2020/05/jquery3.5.0-xss.html
https://jquery.com/upgrade-guide/3.5/
https://api.jquery.com/jQuery.htmlPrefilter/

**Comment by lalumastan** [comment]
I already updated my local copy by adding the new library and updating the following files:

modified:   struts2-jquery-mobile-plugin/src/main/resources/template/mobile/head.ftl
modified:   struts2-jquery-plugin/src/main/resources/template/jquery/head.ftl
deleted:    struts2-jquery-plugin/src/main/resources/template/js/base/jquery-2.2.4.min.js
deleted:    struts2-jquery-plugin/src/main/resources/template/js/base/jquery-2.2.4.min.map
deleted:    struts2-jquery-plugin/src/main/resources/template/js/base/jquery-2.2.4.js
new file:   struts2-jquery-plugin/src/main/resources/template/js/base/jquery-3.6.0.js
new file:   struts2-jquery-plugin/src/main/resources/template/js/base/jquery-3.6.0.min.js
new file:   struts2-jquery-plugin/src/main/resources/template/js/base/jquery-3.6.0.min.map
modified:   struts2-jquery-richtext-plugin/src/site/docs/tinymce.html

So I get necessary access, I can commit those files

**Comment by marwin1991** [comment]
IMO this is one of the most important things to do

**Comment by chinkinsei** [comment]
attached is just blind overwriting the 2.2.4 files with 3.6.0 and it worked for my tiny application.
i am sure its not the correct way to do but its better than nothing done at all.
feel free to try, without any warranties (remove the .zip extension from filename)
[struts2-jquery-plugin-4.0.3r1.jar.zip](https://github.com/struts-community-plugins/struts2-jquery/files/8581609/struts2-jquery-plugin-4.0.3r1.jar.zip)
.

**Comment by sdutry** [comment]
Work has started on a new version that will use JQuery 3.6.0 and struts 6.0.0

**Comment by sdutry** [comment]
related issue #210

**Comment by sdutry** [comment]
part of the upcoming 5.0.0 release which updates jQuery, jQuery-ui and struts
