### ISSUE TITLE
jqGrid change it`s license

### ISSUE THREAD

**Issue by sytolk** [struts-community-plugins/struts2-jquery#20]
http://www.trirand.com/blog/?p=1438

I will be good if its have free (for commercial projects) alternative like http://www.datatables.net

**Comment by sytolk** [comment]
the only one free inline editor for datatables is written for obsolete JQuery version..
https://code.google.com/p/jquery-datatables-editable/

**Comment by rgielen** [comment]
One alternative could be
https://datatables.net/
MIT license, Bootstrap support and options for inline editing

**Comment by sytolk** [comment]
http://www.akshitsethi.me/creating-perfect-tables-with-datatables-and-jeditable-jquery-plugins/

**Comment by jogep** [comment]
I think currently we can just stay with older version of jQgrid and see if
there any forks are coming up.
But anyway support for datatables would also be fine. If i find time I will
try to implement it.
Pull requests are welcome. ;-)

Johannes

#################################################
e-mail: post@jgeppert.com
web: http://www.jgeppert.com
twitter: http://twitter.com/jogep


2015-01-12 13:22 GMT+01:00 Stanimir <notifications@github.com>:

**Comment by afattahi54** [comment]
Your are using 4.6.0 and it seems that we can still upgrade to 4.7.0 ( The last version which the license applies is 4.7.1).
Any way, thanks for plugin :+1:

**Comment by jogep** [comment]
Just upgraded the jqGrid version in 4.0.0-SNAPSHOT to 4.7.0.
