### ISSUE TITLE
struts2-jquery-plugin version

### ISSUE THREAD

**Issue by RicardoDias19** [struts-community-plugins/struts2-jquery#201]
Any new version of struts2-jquery-plugin coming?
The latest version is from 2018... Let me know it: why is this plugin not officially supported by struts2 team?
What are the issues to keep support to it?

**Comment by RicardoDias19** [comment]
I am asking about it 'cause I'd like to know if I can help somehow.

**Comment by sdutry** [comment]
Work has started on a new version that will use JQuery 3.6.0 and struts 6.0.0.

**Comment by sdutry** [comment]
Will be part of the release 5.0.0
