### ISSUE TITLE
struts2-jquery-plugin not compatible with struts 6.0.0

### ISSUE THREAD

**Issue by Farbfetzen** [struts-community-plugins/struts2-jquery#204]
Hello, today I updated struts from 2.5.30 to 6.0.0.

My app compiles and starts fine but when I try to access a page I get the following error:
```
o.a.struts2.components.ClosingUIBean:57 - Could not open template
freemarker.core.ParseException: Syntax error in template "template/jquery/autocompleter.ftl" in line 30, column 47:
Using ?html (legacy escaping) is not allowed when auto-escaping is on with a markup output format (HTML), to avoid double-escaping mistakes.
```

I tried setting the flag `struts.ui.escapeHtmlBody` to `false` but this did not solve the problem. Installing version 4.1.0-SNAPSHOT did not help either.
Do you know if it would somehow be possible to use the plugin with the newest struts? Maybe there is some other flag I overlooked?

When I add the property `<struts2.version>6.0.0</struts2.version>` to the pom of `struts2-jquery-integration-tests` and run `mvn verify` I get lots of similar errors, for example:
```
Caused by: freemarker.core.ParseException: Syntax error in template "template/jquery/div.ftl" in line 22, column 43:
Using ?html (legacy escaping) is not allowed when auto-escaping is on with a markup output format (HTML), to avoid double-escaping mistakes.
```

**Comment by sdutry** [comment]
will be part of the upcoming 5.0.0 

identical to #211
