### ISSUE TITLE
struts2 jquery ajax and client side validation not working together

### ISSUE THREAD

**Issue by afattahi54** [struts-community-plugins/struts2-jquery#21]
This was asked at: http://stackoverflow.com/questions/18684370/struts2-jquery-ajax-and-client-side-validatio-not-working-toghether

The summary is that:
The client side validation should be able to stop the server side ajax be validated, the needed code change has also be presented there.

**Comment by amolghotankar** [comment]
Thanks @afattahi54 Lets hope this gets merged now

**Comment by afattahi54** [comment]
:+1:

**Comment by jogep** [comment]
Thank you for the PR. It is merged in brunch release/4.0.0 now.
