### ISSUE TITLE
gather changes for release notes and documentation updates

### ISSUE THREAD

**Issue by sdutry** [struts-community-plugins/struts2-jquery#271]

**Comment by sdutry** [comment]
# changeLog
- required java version: `8`
- upgrades:
  - `struts` : `6.0.0` 
  - `jQuery`: `3.6.0`
  - `jQuery UI`: `1.13.2`
 - rename `loadfromgoogle `to `loadfromcdn`

# migration guide
- discontinuation of `struts2-jquery-mobile` (since `jQuery Mobile` is discontinued)
- head attribute `loadfromgoogle `was renamed to `loadfromcdn` (jQuery CDN is now used)
- removed deprecated `resizableDelay` and `resizableDistance` 
- removed deprecated `draggableDelay` and `draggableDistance`
- removed deprecated `selectableDelay` and `selectableDistance`
- removed deprecated `sortableDistance` and `sortableDelay`
- removed deprecated `droppableActiveClass` and `droppableHoverClass` in favor of the `classes` attibute
  - for migration: 
  `droppableActiveClass="ui-state-active" dropableHoverClass="ui-state-hover"`
  becomes
 `droppableClasses="{'ui-droppable-active': 'ui-state-active', 'ui-droppable-hover': 'ui-state-hover'}"`

**Comment by jogep** [comment]
Changes added to Wiki: https://github.com/struts-community-plugins/struts2-jquery/wiki/UpgradeGuide
