### ISSUE TITLE
Grid navigator edit dialog does not refresh record when new record is selected

### ISSUE THREAD

**Issue by sfergu** [struts-community-plugins/struts2-jquery#29]
Steps will reproduce the problem

Go to the main grid example at http://struts.jgeppert.com/struts2-jquery-grid-showcase/index.action

1.Select a record in the grid showcase
2. click edit
3. click cancel 
4. select a different record 
5. click edit. note the old record is still in the edit dialog. It should be the newly selected record. 

Is there any way to get the navigator edit dialog to refresh with the newly selected record when it opens? 

Thanks!

**Comment by sfergu** [comment]
I have done some more googling and tried to pass recreateForm:true to my edit and add options for the navigator and still can't achieve reload of the contents of the edit dialog.

 navigatorEditOptions="{
                      width: 450,
                      recreateForm: true,
                      reloadAfterSubmit:true,
                      afterSubmit:function(response,postdata){return isError(response.responseText);}
                    }" 
  navigatorAddOptions="{
                      width: 450,
                      recreateForm: true,
                      reloadAfterSubmit:true,
                      afterSubmit:function(response,postdata){return isError(response.responseText);}
                    }"

Any work around would be greatly appreciated.

**Comment by jogep** [comment]
I upgraded the jqGrid version to 4.7.0 and for me it looks like the error is now gone.
Can you please check that with latest 4.0.0-SNAPSHOT?

**Comment by sfergu** [comment]
The error is gone for me as well. Thanks!
