### ISSUE TITLE
@id with dynamic variable doesn't work anymore

### ISSUE THREAD

**Issue by Dcosmas** [struts-community-plugins/struts2-jquery#308]
Since release 5.0.0 we can't have multiple dialog

```
<%@ taglib prefix="sj" uri="/struts-jquery-tags" %>

<s:iterator value="myBeanList" var="rrSum" status="status">

  <sj:dialog id="dialog%{#status.index}" href="%{ajaxURL}" title="Testing %{#status.index}" />
  <sj:a openDialog="dialog%{#status.index}"><s:property value="#rrSum.rid" /></sj:a>

 </s:iterator>
```
**title** param will be correct --> Testing 1, Testing 3 etc...
but **id** will be dialog%{#status.index} whereas dialog1, dialog2 etc...

what did i miss? Is it a real bug ? or new feature ? :)

**Comment by lukaszlenart** [comment]
`id` has to be unique in the whole document, see [docs](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/id) so this is ok

**Comment by Dcosmas** [comment]
no problem for it to be unique. I just want to generate it myself. 
Or could you explain to me how to have several dialogs in the same page ?
Again with last version of the plugin (4.0.3) this code worked fine and generate one dialog@id by concate the string "dialog" and the variable "%{#status.index}".

**Comment by lukaszlenart** [comment]
Hmmm ... I do not understand, you can change `<sj:dialog id="my_dialog_%{#status.index}_id"` to have your own id, or did you mean that now you get `dialog%{#status.index}` instead of `dialog1`, `dialog2`,...?

**Comment by Dcosmas** [comment]
Absolutely, I mean that now I get dialog%{#status.index} instead of dialog1, dialog2

**Comment by lukaszlenart** [comment]
So this is a bug

**Comment by lukaszlenart** [comment]
Could you try to use `id="%{'dialog' + #status.index}"`?

**Comment by Dcosmas** [comment]
not better :/ 
And I have the same problem with sj:datepicker

but thanks for the try :)

**Comment by sdutry** [comment]
I think i spotted the problem, i'll create a PR for it.

**Comment by lukaszlenart** [comment]
@sdutry you can use [`parameters.escapedId`](https://github.com/apache/struts/blob/master/core/src/main/java/org/apache/struts2/components/UIBean.java#L1035) instead of `parameters.id`
