### ISSUE TITLE
Version 5.0: tabbedpanel is no longer working due to deprecated jqXHR.success

### ISSUE THREAD

**Issue by amellie** [struts-community-plugins/struts2-jquery#313]
``<sj:tabbedpanel>`` is no longer working with the following JS error:

`Uncaught TypeError: e.jqXHR.success is not a function`

This is due to the ``qXHR.success`` function used in [jquery.ui.struts2.js](https://github.com/struts-community-plugins/struts2-jquery/blob/c60a30c2533e1d63476a372bf326754477d17a03/struts2-jquery-plugin/src/main/resources/template/js/struts2/jquery.ui.struts2.js#L382) which has been deprecated by jQuery

Is this something that can be fixed soon?

**Comment by LamseyMcBrien** [comment]
From http://api.jquery.com/jquery.ajax/:
> Deprecation Notice: The jqXHR.success(), jqXHR.error(), and jqXHR.complete() callbacks are removed as of jQuery 3.0. You can use jqXHR.done(), jqXHR.fail(), and jqXHR.always() instead.

We need to update the call from `ui.jqXHR.success()` to `ui.jqXHR.done()` to resolve the reported issue. I've tested this locally by overriding the function with the correct call before triggering the tabbed panel to perform the AJAX action, and it seems to fix the issue.
