### ISSUE TITLE
Incompatibility with struts-annotation ?

### ISSUE THREAD

**Issue by Dcosmas** [struts-community-plugins/struts2-jquery#314]
Since I got struts2-jquery-plugin 5.0.0, I have a dependency with struts-annotation1.0.7.
When I want to build a project that contains a custom taglib I get the message:

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project XXX: Fatal error compiling: java.lang.IllegalArgumentException: 'tlibVersion' is missing -> [Help 1]
    at org.apache.struts.annotations.taglib.apt.TagAnnotationProcessor.checkOptions (TagAnnotationProcessor.java:208)

The taglib is of the form:

<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<taglib xmlns="http://java.sun.com/xml/ns/j2ee" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      version="2.0"
      xsi:schemaLocation="http://java.sun.com/xml/ns/j2ee http://java.sun.com/xml/ns/j2ee/web-jsptaglibrary_2_0.xsd">
      <description><![CDATA["Some custom Cedralis Struts tags "]]></description>
      <display-name>Cedralis Struts Tags</display-name>
      <tlib-version>1.0</tlib-version>
      <short-name>v</short-name>
      <uri>/cedralis-struts-tags</uri>
      <tag>
...

What do you think ? Is it a problem with struts2-jquery-plugin or with struts-annotation ?

Thanks for all !

**Comment by lukaszlenart** [comment]
It's a problem with your configuration, you must provide `tlibVersion` parameter as here
https://github.com/apache/struts/blob/master/core/pom.xml#L111

**Comment by Dcosmas** [comment]
thanks a lot !!!! Have a nice day ! :)
