### ISSUE TITLE
Autocompleter ignores LoadMinimumCount 

### ISSUE THREAD

**Issue by B34v0n** [struts-community-plugins/struts2-jquery#319]
The way I understand the "loadMinimumCount" Attribute for the Autocompleter is, that it doesn't load the autocompletion until the number of characters in the attribute is reached. That's how it worked in Version 4.0.3.
I tested it with the "struts2-jquery-showcase". Click on Widgets, Autocompleter, AutocompleterJSON. (Because there, the "loadMinimumCount" is set to 2.
In the new Version on the Website (Version 5.0.1) http://struts.jgeppert.com/struts2-jquery-showcase/index.action it immediatly shows me the autocomplete possibilities, as soon as I start typing.
In Version 4.0.3, it shows me no autocomplete suggestions until I typed 2 characters.

Is the new behavior desired? Or is it a bug?
Thanks in Advance

**Comment by B34v0n** [comment]
![autocomplete](https://user-images.githubusercontent.com/88542001/198275506-9db042f3-e740-421e-aaca-b05e474894de.gif)

**Comment by lukaszlenart** [comment]
I tied to investigate what's wrong, but find nothing. The generated JS has all the options:

```javascript
jQuery(document).ready(function () {
  var options_languages_widget = {};
  ...
  options_languages_widget.minLength = 2;
  ...
```

and applies them the the widget, yet this options doesn't work. If I manually applied the option using 

```javascript
$('#languages_widget').autocomplete({minLength: 2});
```

everything works :\

**Comment by B34v0n** [comment]
I had some timing Issues with `jQuery(document).ready()` lately, could changing that to `$( window ).on( "load")` maybe help with it?

**Comment by lukaszlenart** [comment]
I checked that, everything is fine, other options (like `delay`) are applied, just `minLength` is not. Did that ever work before?

**Comment by B34v0n** [comment]
Ok, that's strange.
Yes, it worked with Version 4.0.3 perfectly. It just "broke" with the Update to Version 5.0.1. in the gif I posted, you can see, that it worked in the showcase in version 4.0.3 as well.

**Comment by lukaszlenart** [comment]
I found it :) Looks like previously it was `minimum` option in JQuery UI and now is `minLength` (there is an intermediate layer which _translates_ options between Struts and JQuery UI)

**Comment by B34v0n** [comment]
Wow that's great! Thank you. It's always the small things. :D
