### ISSUE TITLE
Struts 2 jquery plugin set style the checkbox name and value

### ISSUE THREAD

**Issue by afattahi54** [struts-community-plugins/struts2-jquery#32]
There is a struts 2 form which has a grid in it. The grid has check box for each row which is enabled by setting `sjg:grid multiselect="true"`.

The generated grid has checkboxs. But the checkboxs have different name and they do not have any value.

The checkboxes which I used so far have below structure (Same `name`, Different `value`):

    <input type="checkbox" name="vehicle" value="Bike"> I have a bike<br>
    <input type="checkbox" name="vehicle" value="Car" checked> I have a car<br>

But the generated html in jqGrid is as:

    <input id="jqg_gridtable_2" class="cbox" name="jqg_gridtable_2" type="checkbox">

Is it possible to style the checkbox?!

I can solve above with `formatter`, but I wonder if it can be done easier?!

**Comment by jogep** [comment]
Yes of course, you can just use the class name to style it:

	.cbox {
		style: value;
	}

**Comment by afattahi54** [comment]
Sorry may be I ask it bad !!
I want to set the jqgird so the generated check boxes have unique name and different value
