### ISSUE TITLE
Issue with sj:dialog @title

### ISSUE THREAD

**Issue by Dcosmas** [struts-community-plugins/struts2-jquery#320]
In dialog title we can have plain text so in line 53 in dialog-close.ftl I think we should have :

options_${escapedOptionId}.title = "<#outputformat "JavaScript">${parameters.title}</#outputformat>";

instead of 

options_${escapedOptionId}.title = "${parameters.title}";

In my case with french word like "l'annuaire" I had "l& # 3 9 ; annuaire" :(

**Comment by lukaszlenart** [comment]
> In my case with french word like "l'annuaire" I had "l'annuaire" :(

Probably you are right, but I don't see a difference tbh

**Comment by Dcosmas** [comment]
github wysywyg translate &#39 ; lol
