### ISSUE TITLE
Struts 6.0.3 + struts2-jquery-plugin 5.0.1: not found struts/js/calendar.gif

### ISSUE THREAD

**Issue by ZhigunovSemen** [struts-community-plugins/struts2-jquery#326]
Hi, 

The problem is when using <@sj.datepicker> the link of buttom image (usually calendar.gif) refers to a non-existing place.

In my case (i do not use _buttonImage_ tag and image should be default) it's `/struts/js/calendar.gif` - but correct path is `/static/js/calendar.gif`

generated html looks like this:
```
<button type="button" class="ui-datepicker-trigger">
  <img src="/struts/js/calendar.gif" alt="..." title="...">
</button>
```

The most illustrative example is this case reproduced in **Struts2 jQuery Plugin Showcase** page
https://struts.jgeppert.com/struts2-jquery-showcase/index.action
You will found same problem on Widgets -> Datepicker

See attached screenshot for details. 

Is this a configuration problem or bug ?

<img width="712" alt="Screenshot 2022-12-15 at 00 38 13" src="https://user-images.githubusercontent.com/25611597/207723670-918c9e83-8a15-492f-a708-3af26effd6e6.png">

**Comment by lukaszlenart** [comment]
See #321 - the issue is fixed but not released yet
