### ISSUE TITLE
Disable auto escape for Dialog and DataTable

### ISSUE THREAD

**Issue by awalvekar1** [struts-community-plugins/struts2-jquery#328]
Please disable auto escaping for the property **position** of **Dialog** widget.
`position="{ my: 'center', at: 'top', of: window }"` gets escaped as `options_opocDialog.position = { my: &#39;center&#39;, at: &#39;top&#39;, of: window };`
Similar is encountered in the property **dom** of **DataTable** widget.
`dom= "<'col-auto'B>"` gets escaped as `options_usersTable.dom = "&lt;&#39;col-auto&#39;B&gt;";`

This issue is similar to #284

**Comment by awalvekar1** [comment]
Will there be a fix available for this issue in the SNAPSHOPT ?

**Comment by lukaszlenart** [comment]
Yes, it will be.

**Comment by awalvekar1** [comment]
Thank you.

**Comment by lukaszlenart** [comment]
Relates to #320
