### ISSUE TITLE
Cannot download 5.0.3-SNAPSHOT

### ISSUE THREAD

**Issue by afattahi54** [struts-community-plugins/struts2-jquery#329]
I wanted to test a bug on the `5.0.3-SNAPSHOT` but the files seems not are deployed on sonatype server.

I have also checked https://oss.sonatype.org/content/groups/staging/com/jgeppert/struts2/jquery/struts2-jquery/ url and could not find it there.

I have this on the `pom.xml`

             <dependency>
			<groupId>com.jgeppert.struts2.jquery</groupId>
			<artifactId>struts2-jquery-plugin</artifactId>
			<version>5.0.3-SNAPSHOT</version>
		</dependency>
               
		<repository>
			<id>sonatype.oss.snapshots</id>
			<name>Sonatype OSS Snapshot Repository</name>
			<url>http://oss.sonatype.org/content/repositories/snapshots</url>
			<releases>
				<enabled>false</enabled>
			</releases>
			<snapshots>
				<enabled>true</enabled>
			</snapshots>
		</repository>

**Comment by lukaszlenart** [comment]
@jogep I think only you can upload the SNAPSHOT version or can we extend the GH Actions workflow?

**Comment by jogep** [comment]
On the road at the moment. Will update SNAPSHOT version when I'm back at the end of the week.

**Comment by jogep** [comment]
Latest 5.0.3 SNAPSHOT should be know available.
