### ISSUE TITLE
Datatable configuration does not work

### ISSUE THREAD

**Issue by nikosdimitrakas** [struts-community-plugins/struts2-jquery#335]
Since upgrading from 4.x to 5.x, specifying configurations like searching="false" info="false" paging="false" and autoWidth="false" don't have any effect.
We have tried 5.0.1 and 5.0.2 and also the unreleased changes to datatables-close.ftl
The class DatatablesTag has not changed since 2018, so where is this change in behaviour coming from?
It seems that the javascript that is generated immediately after the closing tag for the table is not including all the flags. theme, jqueryaction, id, order and others are included, but not autoWidth, info, paging and searching. It worked fine until version 4.1.0-SNAPSHOT
It seems that the changes from 2022-10-17 may have caused this. Only the parameters that are booleans seem to have stopped working.

**Comment by nikosdimitrakas** [comment]
This probably relates to the bug described at https://freemarker.apache.org/docs/dgui_template_exp.html#dgui_template_exp_missing_default

?default(v) has been replaced by !v but the expressions should be inside parentheses to avoid evaluation of == before !

For example
<#if parameters.autoWidth!true == false>
should be
<#if (parameters.autoWidth!true) == false>
or back to the deprecated version
<#if parameters.autoWidth?default(true) == false>

**Comment by lukaszlenart** [comment]
Thanks @nikosdimitrakas for pointing this out, could you review the attached PR?

**Comment by nikosdimitrakas** [comment]
I tested your changes and they fix the issue.

**Comment by lalumastan** [comment]
@lukaszlenart  Appreciate your prompt response.  When can we expect the 5.0.3 release?

**Comment by lukaszlenart** [comment]
Hopefully soon :) There is on issue with jqgrid I would like to investigate and maybe address in 5.0.3
