### ISSUE TITLE
DevTools failed to load source map: Could not load content for  ... jquery.ui.struts2.min.js.map

### ISSUE THREAD

**Issue by lalumastan** [struts-community-plugins/struts2-jquery#340]
I did a nightly build locally for 5.0.3.SNAPSHOT.  Library seems to be working as expected so far.  However, I noticed the following warnings on browser's JS console log and wondering what I have missed during the maven build steps (i.e. clean package):

DevTools failed to load source map: Could not load content for .../jquery.ui.struts2.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

**Comment by lukaszlenart** [comment]
Could you post the full path? Maybe it is related to static path change from `/struts` to `/static`

**Comment by lalumastan** [comment]
> Could you post the full path? Maybe it is related to static path change from `/struts` to `/static`

This error was based on the 5.0.3.SNAPSHOT I had to build back in March.  I just cloned a fresh version 5.0.4.SNAPSHOT and I did not notice that error/warning yet.  I appreciate you checking this.
