### ISSUE TITLE
Deprecated use of isFunction

### ISSUE THREAD

**Issue by nikosdimitrakas** [struts-community-plugins/struts2-jquery#342]
There is a call the isFunction at line 92 in jquery.subscribe.js that according to JQuery-Migrate is deprecated. 
According to https://github.com/jquery/jquery-migrate/blob/main/warnings.md the solution is
`Replace any use of jQuery.isFunction( x ) with typeof x === "function"`

**Comment by lukaszlenart** [comment]
but as far I understand this is a JQuery library not a custom thing in the plugin? I wouldn't change what JQuery offers and rather upgrade to the latest version if available - @jogep @sdutry any opinion?

**Comment by jogep** [comment]
@lukaszlenart this is not part of jQuery itself. Was a custom third party plugin which I extended a while ago.

https://github.com/struts-community-plugins/struts2-jquery/blob/release/5.0.x/struts2-jquery-plugin/src/main/resources/template/js/plugins/jquery.subscribe.js

Will check if I can provide this for the next version.

**Comment by jogep** [comment]
Fixed with new release 5.0.3
