### ISSUE TITLE
can not use sj:select without using sj:autocompleter

### ISSUE THREAD

**Issue by hss-ch** [struts-community-plugins/struts2-jquery#345]
Hi,
I am trying to migrate to Struts2 jQuery Plugin 5.0.3.
I want to use the tag sj:select with attribute autocomplete="true" for auto completion.
But the tag sj:select with attribute autocomplete="true" is not working , without using sj:autocompleter tag in the same jsp page.

**Comment by lukaszlenart** [comment]
Please see the linked issue #346 and the PR #347
