### ISSUE TITLE
Column resize upto 1 px

### ISSUE THREAD

**Issue by pramodtiwari** [struts-community-plugins/struts2-jquery#41]
Hello
i want to re-size grid column up-to 1px. but at the time re-sizing something fixed in plugin so i can not able to re-size up-to 1px.
please give me any solution.from where i can fixed this solution for all Grid Column.
![resize](https://cloud.githubusercontent.com/assets/8870194/14905503/1e9eeb70-0dec-11e6-9648-22476be8b7ed.JPG)

I attach image file.please check it.

Thank you...

**Comment by jogep** [comment]
Please use your bowser debugger to find the correct class for overrides.
