### ISSUE TITLE
Struts 2.5 unsupported?

### ISSUE THREAD

**Issue by matorodriguez** [struts-community-plugins/struts2-jquery#42]
When upgrading to Struts 2.5, I'm getting a TemplateNotFoundException (for the sj:div tag for example) using the plugin (version 3.7.1).

**Comment by jogep** [comment]
version 4.0 will be compatible to struts 2.5

**Comment by matorodriguez** [comment]
great, thanks!
is there a guess about when it'll be released?
thanks again.

**Comment by afattahi54** [comment]
+1

**Comment by amolghotankar** [comment]
+1

On Sat, May 14, 2016 at 8:06 PM, afattahi54 <notifications@github.com>
wrote:

> +1
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/struts-community-plugins/struts2-jquery/issues/42#issuecomment-219223593>
>



-- 



*With Best Regards,*

Amol Ghotankar
Technical Lead
M: +91 9960 980 419 <http://www.cursivetech.com>

**Comment by jogep** [comment]
@matorodriguez like every open source project. It is done when it is done! :-)
Sorry can not give a concrete timeline. But PR's are welcome. ;-)

**Comment by iashkan** [comment]
+1

**Comment by animgr** [comment]
+1

**Comment by mahyarevafa** [comment]
+1

**Comment by jogep** [comment]
First available SNAPSHOT build 4.0.1-SNAPSHOT is available and compatible to Struts 2.5

**Comment by matorodriguez** [comment]
Hi! Thank you very much for that Jogep.
I noted that a new dependency is present: log4j:log4j:jar:1.2.17:compile, while it's not a dependency in struts2-jquery-plugin 3.7.1 nor 4.0.0-SNAPSHOT.
Is it really neccesary? Struts 2.5 just drags in log4j-api, I believe that's for not being tied to a logging implementation.
Thanks!

**Comment by jogep** [comment]
Version 2.5.1 with support for Struts 2.5 is released
