### ISSUE TITLE
Can not use sj:select tag directly in Struts2 jQuery Plugin 5.0.4-SNAPSHOT

### ISSUE THREAD

**Issue by hss-ch** [struts-community-plugins/struts2-jquery#447]
I just started the showcase locally with the latest Snapshot-Version. The problem is not solved. The tag sj:select with attribute autocomplete="true" is not working, without using sj:autocompleter tag in the same jsp page.

When I removed sj:autocompleter tag in the jsp page and used only sj:select tag with attribute autocomplete="true", the sj:select is not working with the following error.
![image](https://github.com/struts-community-plugins/struts2-jquery/assets/63054387/0b706417-e3fb-4fb0-b3d1-ed90207cfc85)

**Comment by lukaszlenart** [comment]
Duplicates #409
