### ISSUE TITLE
sj:autocompleter does not properly handle cssErrorClass.

### ISSUE THREAD

**Issue by Naros** [struts-community-plugins/struts2-jquery#46]
When validating the content of a submitted form, I am attempting to properly specify that an autocompleter field is in error using the `cssErrorClass` struts attribute as follows:

```
<sj:autocompleter
  cssErrorClass="field-error"
  name="productId"
  list="productNameIdMap"
/>
```

In the above code, the action supplies a `Map<ProductId,String>` which uses the combobox plugin to render the autocompleter widget.  The corresponding `select` which is hidden in this case has had the error class applied to it; however the widget users interact with is the s2j-combox-input.  

The cssErrorClass should be applied to the s2j-combox-input input field as well.

**Comment by flofourcade** [comment]
PR #138
