### ISSUE TITLE
Upgrade jQuery jstree to 3.0.1

### ISSUE THREAD

**Issue by calbiston** [struts-community-plugins/struts2-jquery#5]
Upgrade jQuery jstree from 1.0-rc3 to 3.0.1.

**Comment by flofourcade** [comment]
Looked at jstree changelog. No breaking API change between 3.1.1 (current jstree version in jquery plugin 4.0.1 branch ) and 3.3.1, only bugfixes, new plugins, new config options and performance improvement.
Did some tests with jquery struts 2 showcase and some private projects using struts2-jquery-jstree-plugin, I didn't have any issue.
Seems possible to upgrade to 3.3.1 safely.
