### ISSUE TITLE
AM/PM not working

### ISSUE THREAD

**Issue by yhjhoo** [struts-community-plugins/struts2-jquery#51]
With this code

<sj:datepicker id="time2" label="With AM/PM" timepicker="true" timepickerAmPm="true"/>
It always show 24 hour format

Even the demo doesn't work
http://struts.jgeppert.com/struts2-jquery-showcase/index.action

**Comment by flofourcade** [comment]
with `timepickerAmPm="true"` you have to add a `timepickerFormat` attribute to let the addon know where to put AM/PM info.
It seems that the default format isn't modified when `timepickerAmPm="true"` is specified.
eg
```html
<sj:datepicker id="time2" label="With AM/PM" timepicker="true" timepickerAmPm="true "
timepickerFormat="hh:mm:ss TT"/>
```
will add AM or PM at the end of the time.
Use tt for lowercase and t or T for a/p or A/P
