### ISSUE TITLE
working demo/example for datatables plugin

### ISSUE THREAD

**Issue by prabhu-mannu** [struts-community-plugins/struts2-jquery#56]
is there any working demo/example for datatables plugin ??

by the way great job on creating these plugins, really appreciate what you are doing.

**Comment by jogep** [comment]
You can run the current development version of the showcase application. This include and database example.

**Comment by flofourcade** [comment]
There 's a lot of examples on Datatables' official website. If some of them seem particulary interesting, tell me and I'll add them to the jquery plugin showcase, using sjdt:datatables tag.

**Comment by prabhu-mannu** [comment]
@jogep  thank you very much, 
@flofourcade  I am trying to something like this https://datatables.net/examples/api/multi_filter.html
with server side filtering.

**Comment by flofourcade** [comment]
OK, interesting use case, I've thinked about it, but no time to test it.
You'll have to use the serverside processing demo in the showcase as a starting point.
Then use jquery to inject search textfields in the footer, and to add search triggering with datatable API as shown in the multi_filter sample. Next you'll have to customize the server side action to add the multi search logic. Search params should be avalaible in the ServerSideProcessingRequest object.
I'm in holiday for now, so cannot give a solution "out of the box". Please test it, if there's any problem I'll help ASAP.

**Comment by prabhu-mannu** [comment]
@flofourcade 
thank you very much for your input, i will try to get it working.   Basically i need some starting point on 
how to use this plugin. Will post here if need any help.
Please enjoy your holiday, really appreciate that you are taking time to answer my questions during your holiday.
