### ISSUE TITLE
Nexus Repositories and Maven Builds

### ISSUE THREAD

**Issue by aeonoftime** [struts-community-plugins/struts2-jquery#57]
Beyond version 3.7.1 MVN Central and other repositories are not listing more current builds. Is there a work around on this or do we need to do something to get these builds to pull the jars down?

**Comment by jogep** [comment]
You can use the latest SNAPSHOT releases for version 4.0.1-SNAPSHOT

https://oss.sonatype.org/content/repositories/snapshots/com/jgeppert/struts2/jquery/

Until version 4.0.1 is finished you can only use more uptodate SNAPSHOT versions.
