### ISSUE TITLE
Version 5.0.5 requires JDK 17

### ISSUE THREAD

**Issue by afattahi54** [struts-community-plugins/struts2-jquery#572]
I have downloaded to version 5.0.5 and it seems that it is compiled with version 17. 

```java
java.lang.UnsupportedClassVersionError: com/jgeppert/struts2/jquery/chart/views/JqueryChartTagLibrary 
has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java
 Runtime only recognizes class file versions up to 52.0 (unable to load class 
[com.jgeppert.struts2.jquery.chart.views.JqueryChartTagLibrary])
```

I reviewed the release note and I did not find any issue related to this upgrade. 
Will this be fixed or we need to upgrade jdk

Thanks

**Comment by sepe81** [comment]
Good catch. IMHO it comes from 14596d78c678a2a52f521df2a55c6b5ea5e1f352

@lukaszlenart Maybe we could revert those two lines to Java 8 compatibility and upgrade the Java baseline with the next major release?

		<maven.compiler.source>17</maven.compiler.source>
		<maven.compiler.target>17</maven.compiler.target>

**Comment by lukaszlenart** [comment]
Hm... I think this was related to some dependencies. And yeah it should be rather 5.1 instead of 5.0.5

**Comment by lukaszlenart** [comment]
It was because of Selenium, I can revert but anyway we must switch to JDK17 in case of Struts 7.

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.13.0:testCompile (default-testCompile) on project struts2-jquery-integration-tests: Compilation failure
[ERROR] ../struts2-jquery/struts2-jquery-integration-tests/src/test/java/com/jgeppert/jquery/AbstractJQueryTest.java:[9,26] error: cannot access WebDriver
[ERROR]   bad class file: ../.m2/repository/org/seleniumhq/selenium/selenium-api/4.26.0/selenium-api-4.26.0.jar(org/openqa/selenium/WebDriver.class)
[ERROR]     class file has wrong version 55.0, should be 52.0
[ERROR]     Please remove or make sure it appears in the correct subdirectory of the classpath.
```

**Comment by sepe81** [comment]
I propose creating a new 5.0.6 release with Java 8 compatibility. After that, we could update the version to 5.1.0-SNAPSHOT and set Java 17 as the minimum requirement. This issue could then be resolved with the 5.0.6 release.

@lukaszlenart What are your thoughts?

**Comment by lukaszlenart** [comment]
Make sense, I will prepare a new release

**Comment by lukaszlenart** [comment]
Done, please verify
https://github.com/struts-community-plugins/struts2-jquery/releases/tag/5.0.6
