### ISSUE TITLE
 Generating `nonce` for generated scripts

### ISSUE THREAD

**Issue by afattahi54** [struts-community-plugins/struts2-jquery#582]
We are trying to set the `Content-Security-Policy` to `script-src 'self'` in our web based application., but we face issues.
As the  jquery-plugin library dynamically generates inline scripts, it is not possible to add this header.

As I find this can be handled by adding `nonce` to `<script>`. `https://content-security-policy.com/nonce/`

Is it possible that we configure struts jQuery tags to generate nonce

**Comment by lukaszlenart** [comment]
`<s:script/>` should do it already, how do you use the plugin? The plugin has been already adjusted, see #318

**Comment by afattahi54** [comment]
I see tags generates scripts like below (without nonce):

````js
<script type="text/javascript">
jQuery(document).ready(function () {
	var options_anchor_991965924 = {};
	options_anchor_991965924.jqueryaction = "anchor";
	options_anchor_991965924.id = "anchor_991965924";
	options_anchor_991965924.targets = "helpPlaceHolder";
	options_anchor_991965924.href = "/guidance/contact-us.ib";
	options_anchor_991965924.listentopics = "contact-us";

jQuery.struts2_jquery.bind(jQuery('#anchor_991965924'),options_anchor_991965924);

 });
</script>
````

I am using version `5.0.6`

**Comment by lukaszlenart** [comment]
Could you be more specific and share the exact tag you are using? And also please be aware that browser's Inspect function doesn't show `nonce`, you must view the source:

![image](https://github.com/user-attachments/assets/46bb22a6-40e3-4357-9f65-194f4475d1c1)


```
<script type="text/javascript" nonce="cbI7VVeFZDetJJQlbsjOfK6Z">
jQuery(document).ready(function () {
	var options_ajaxmenulink = {};
	options_ajaxmenulink.jqueryaction = "anchor";
	options_ajaxmenulink.id = "ajaxmenulink";
	options_ajaxmenulink.targets = "menu";
	options_ajaxmenulink.href = "/struts2-jquery-showcase/showcase-menu-ajax.action";

jQuery.struts2_jquery.bind(jQuery('#ajaxmenulink'),options_ajaxmenulink);
 });
```

**Comment by afattahi54** [comment]
I have not added the `<interceptor-ref name="csp" >`  as mentioned in [](https://struts.apache.org/core-developers/csp-interceptor#examples)
