### ISSUE TITLE
5.0.x (JDK 8) not compatible with struts 6.7.0

### ISSUE THREAD

**Issue by assachs** [struts-community-plugins/struts2-jquery#583]
Hello,
can you please create a struts-jquery-release compatible with struts 6.7.0 and jdk 8 (version 5.0.x)?

Backgrund:
Struts 6.7.0 changed "parameters" to "attributes" (https://issues.apache.org/jira/browse/WW-5465) which breaks struts-jquery.  This is already fixed in https://github.com/struts-community-plugins/struts2-jquery/pull/581 but the current struts-jquery-version is 5.1.x with jdk 17.

Thank you for your work on struts /struts-jquery.

**Comment by gregh3269** [comment]
Struts 7.0 changed "parameters" to "attributes", not Struts 6.7.0.

**Comment by afattahi54** [comment]
Struts 6.7.0 and Struts jquery pluing 5.0.6 works fine together

**Comment by assachs** [comment]
Are you sure? See build failure on https://github.com/struts-community-plugins/struts2-jquery/pull/579 and Lukas comment here https://issues.apache.org/jira/browse/WW-5465. I will double check

**Comment by assachs** [comment]
e.g.: 
com.jgeppert.struts2.jquery.components.Menu
Line 142:            list = parameters.get(PARAM_LIST); 

parameters not found. It's now attributes.

**Comment by assachs** [comment]
Stack trace:
Caused by: java.lang.NoSuchFieldError: parameters
	at com.jgeppert.struts2.jquery.components.Menu.evaluateExtraParams(Menu.java:142)
	at org.apache.struts2.components.UIBean.evaluateParams(UIBean.java:876)

**Comment by assachs** [comment]
> Struts 7.0 changed "parameters" to "attributes", not Struts 6.7.0.

No, the change of protected field parameters to attributes in class Component is in 6.7.0. This field is used by struts jquery (e.g. Menu).

**Comment by lukaszlenart** [comment]
I prepared a PR to revert to Java 8 -> #584, once merged I'm going to merge also #581 and release a new 5.0.x version.
