### ISSUE TITLE
What is the remaining work that needs to be done before version 4.0.1 can be released?

### ISSUE THREAD

**Issue by sdutry** [struts-community-plugins/struts2-jquery#78]
I was just wondering what remains to be done before a version of the plugin that's compatible with struts 2.5.x

Looking at the issues that are part of the [4.0.1 milestone](https://github.com/struts-community-plugins/struts2-jquery/milestone/2), it looks like most of the issues have been resolved.

Is there more work that needs to be done before a release will be made?
If so, is it possible to list what still needs to happen?

This would make it easy to see where i could possible offer some help with.

**Comment by jogep** [comment]
Thank you for the help offer. Right now there is one issue left after upgrading to latest TinyMCE version I like to fix. If you open in the showcase the TinyMCE example it works but when you the navigate somewhere else and come back then the editor is not initialized again.

Also I was thinking about supporting the new jQuery UI widget Selectmenu:

**Comment by sdutry** [comment]
@jogep 
concerning the TinyMCE editor, could this be the cause?
http://stackoverflow.com/questions/32519169/why-tinymce-fails-to-load-second-time

there, the selector was missing.

**Comment by flofourcade** [comment]
@jogep @sdutry 
Fixed tinyMCE issue, it works for me,please tell me if it works for you too so I can pass the issue as resolved

**Comment by jogep** [comment]
Version 4.0.1 is now released! Special thank you to @flofourcade and @sdutry for your contributions on this version.
