### ISSUE TITLE
Errors when trying to load dialogs/sliders

### ISSUE THREAD

**Issue by matorodriguez** [struts-community-plugins/struts2-jquery#89]
Since the snapshot 20161124.181023-12 (including release 4.0.1 too), I'm getting errors when trying to load dialogs/sliders.
I used the following browsers:
	Chrome: 54.0.2840.99 m (64-bit)
	Firefox: 50.0.2

**DIALOG**
	Example:
```
		<%@ taglib prefix="sj" uri="/struts-jquery-tags" %>
		<sj:head locale="es" jquerytheme="start"/>
		<sj:dialog id="mydialog" title="Dialog with local content">
		    Mauris mauris ante, blandit et, ultrices a, suscipit eget, quam. Integer ut neque. Vivamus nisi metus, molestie vel, gravida in, condimentum sit amet, nunc. Nam a nibh. Donec suscipit eros. Nam mi. Proin viverra leo ut odio. Curabitur malesuada. Vestibulum a velit eu ante scelerisque vulputate.
		</sj:dialog>
```
	Chrome console errors:

> 		VM408:1 Uncaught TypeError: b.widget is not a function(…)(anonymous function) @ VM408:1(anonymous function) @ VM408:1(anonymous function) @ VM408:1globalEval @ jquery-2.2.4.min.js:2text script @ jquery-2.2.4.min.js:4Ab @ jquery-2.2.4.min.js:4z @ jquery-2.2.4.min.js:4(anonymous function) @ jquery-2.2.4.min.js:4send @ jquery-2.2.4.min.js:4ajax @ jquery-2.2.4.min.js:4(anonymous function) @ jquery.struts2.min.js?s2j=4.0.1:21each @ jquery-2.2.4.min.js:2require @ jquery.struts2.min.js?s2j=4.0.1:21dialog @ VM407:28bind @ jquery.struts2.min.js?s2j=4.0.1:30(anonymous function) @ logout:53i @ jquery-2.2.4.min.js:2fireWith @ jquery-2.2.4.min.js:2ready @ jquery-2.2.4.min.js:2J @ jquery-2.2.4.min.js:2
> 		VM410:8 Uncaught TypeError: Cannot set property 'position' of undefined(…)(anonymous function) @ VM410:8(anonymous function) @ VM410:12(anonymous function) @ VM410:1(anonymous function) @ VM410:1globalEval @ jquery-2.2.4.min.js:2text script @ jquery-2.2.4.min.js:4Ab @ jquery-2.2.4.min.js:4z @ jquery-2.2.4.min.js:4(anonymous function) @ jquery-2.2.4.min.js:4send @ jquery-2.2.4.min.js:4ajax @ jquery-2.2.4.min.js:4(anonymous function) @ jquery.struts2.min.js?s2j=4.0.1:21each @ jquery-2.2.4.min.js:2require @ jquery.struts2.min.js?s2j=4.0.1:21dialog @ VM407:28bind @ jquery.struts2.min.js?s2j=4.0.1:30(anonymous function) @ logout:53i @ jquery-2.2.4.min.js:2fireWith @ jquery-2.2.4.min.js:2ready @ jquery-2.2.4.min.js:2J @ jquery-2.2.4.min.js:2
> 		VM413:1 Uncaught TypeError: Cannot read property 'mouse' of undefined(…)(anonymous function) @ VM413:1(anonymous function) @ VM413:1(anonymous function) @ VM413:1globalEval @ jquery-2.2.4.min.js:2text script @ jquery-2.2.4.min.js:4Ab @ jquery-2.2.4.min.js:4z @ jquery-2.2.4.min.js:4(anonymous function) @ jquery-2.2.4.min.js:4send @ jquery-2.2.4.min.js:4ajax @ jquery-2.2.4.min.js:4(anonymous function) @ jquery.struts2.min.js?s2j=4.0.1:21each @ jquery-2.2.4.min.js:2require @ jquery.struts2.min.js?s2j=4.0.1:21dialog @ VM407:28bind @ jquery.struts2.min.js?s2j=4.0.1:30(anonymous function) @ logout:53i @ jquery-2.2.4.min.js:2fireWith @ jquery-2.2.4.min.js:2ready @ jquery-2.2.4.min.js:2J @ jquery-2.2.4.min.js:2
> 		VM414:1 Uncaught TypeError: Cannot set property 'focusable' of undefined(…)(anonymous function) @ VM414:1(anonymous function) @ VM414:1(anonymous function) @ VM414:1globalEval @ jquery-2.2.4.min.js:2text script @ jquery-2.2.4.min.js:4Ab @ jquery-2.2.4.min.js:4z @ jquery-2.2.4.min.js:4(anonymous function) @ jquery-2.2.4.min.js:4send @ jquery-2.2.4.min.js:4ajax @ jquery-2.2.4.min.js:4(anonymous function) @ jquery.struts2.min.js?s2j=4.0.1:21each @ jquery-2.2.4.min.js:2require @ jquery.struts2.min.js?s2j=4.0.1:21dialog @ VM407:28bind @ jquery.struts2.min.js?s2j=4.0.1:30(anonymous function) @ logout:53i @ jquery-2.2.4.min.js:2fireWith @ jquery-2.2.4.min.js:2ready @ jquery-2.2.4.min.js:2J @ jquery-2.2.4.min.js:2
> 		VM415:1 Uncaught TypeError: Cannot set property 'keyCode' of undefined(…)(anonymous function) @ VM415:1a.ui.keyCode.BACKSPACE @ VM415:1(anonymous function) @ VM415:1globalEval @ jquery-2.2.4.min.js:2text script @ jquery-2.2.4.min.js:4Ab @ jquery-2.2.4.min.js:4z @ jquery-2.2.4.min.js:4(anonymous function) @ jquery-2.2.4.min.js:4send @ jquery-2.2.4.min.js:4ajax @ jquery-2.2.4.min.js:4(anonymous function) @ jquery.struts2.min.js?s2j=4.0.1:21each @ jquery-2.2.4.min.js:2require @ jquery.struts2.min.js?s2j=4.0.1:21dialog @ VM407:28bind @ jquery.struts2.min.js?s2j=4.0.1:30(anonymous function) @ logout:53i @ jquery-2.2.4.min.js:2fireWith @ jquery-2.2.4.min.js:2ready @ jquery-2.2.4.min.js:2J @ jquery-2.2.4.min.js:2
> 		VM417:1 Uncaught TypeError: Cannot set property 'safeActiveElement' of undefined(…)(anonymous function) @ VM417:1a.ui.safeActiveElement.b @ VM417:1(anonymous function) @ VM417:1globalEval @ jquery-2.2.4.min.js:2text script @ jquery-2.2.4.min.js:4Ab @ jquery-2.2.4.min.js:4z @ jquery-2.2.4.min.js:4(anonymous function) @ jquery-2.2.4.min.js:4send @ jquery-2.2.4.min.js:4ajax @ jquery-2.2.4.min.js:4(anonymous function) @ jquery.struts2.min.js?s2j=4.0.1:21each @ jquery-2.2.4.min.js:2require @ jquery.struts2.min.js?s2j=4.0.1:21dialog @ VM407:28bind @ jquery.struts2.min.js?s2j=4.0.1:30(anonymous function) @ logout:53i @ jquery-2.2.4.min.js:2fireWith @ jquery-2.2.4.min.js:2ready @ jquery-2.2.4.min.js:2J @ jquery-2.2.4.min.js:2
> 		VM418:1 Uncaught TypeError: Cannot set property 'safeBlur' of undefined(…)(anonymous function) @ VM418:1(anonymous function) @ VM418:1(anonymous function) @ VM418:1globalEval @ jquery-2.2.4.min.js:2text script @ jquery-2.2.4.min.js:4Ab @ jquery-2.2.4.min.js:4z @ jquery-2.2.4.min.js:4(anonymous function) @ jquery-2.2.4.min.js:4send @ jquery-2.2.4.min.js:4ajax @ jquery-2.2.4.min.js:4(anonymous function) @ jquery.struts2.min.js?s2j=4.0.1:21each @ jquery-2.2.4.min.js:2require @ jquery.struts2.min.js?s2j=4.0.1:21dialog @ VM407:28bind @ jquery.struts2.min.js?s2j=4.0.1:30(anonymous function) @ logout:53i @ jquery-2.2.4.min.js:2fireWith @ jquery-2.2.4.min.js:2ready @ jquery-2.2.4.min.js:2J @ jquery-2.2.4.min.js:2
> 		VM423:1 Uncaught TypeError: d.widget is not a function(…)(anonymous function) @ VM423:1(anonymous function) @ VM423:1(anonymous function) @ VM423:1globalEval @ jquery-2.2.4.min.js:2text script @ jquery-2.2.4.min.js:4Ab @ jquery-2.2.4.min.js:4z @ jquery-2.2.4.min.js:4(anonymous function) @ jquery-2.2.4.min.js:4send @ jquery-2.2.4.min.js:4ajax @ jquery-2.2.4.min.js:4(anonymous function) @ jquery.struts2.min.js?s2j=4.0.1:21each @ jquery-2.2.4.min.js:2require @ jquery.struts2.min.js?s2j=4.0.1:21dialog @ VM407:28bind @ jquery.struts2.min.js?s2j=4.0.1:30(anonymous function) @ logout:53i @ jquery-2.2.4.min.js:2fireWith @ jquery-2.2.4.min.js:2ready @ jquery-2.2.4.min.js:2J @ jquery-2.2.4.min.js:2
> 		VM426:7 Uncaught TypeError: d.ui.safeActiveElement is not a function(…)

**SLIDER**
	Example:
```
		<%@ taglib prefix="sj" uri="/struts-jquery-tags" %>
		<sj:head locale="es" jquerytheme="start"/>
		<sj:slider id="simpleslider"/>
```
	Chrome console errors:

> 		VM45:1 Uncaught TypeError: b.widget is not a function(…)(anonymous function) @ VM45:1(anonymous function) @ VM45:1(anonymous function) @ VM45:1globalEval @ jquery-2.2.4.min.js:2text script @ jquery-2.2.4.min.js:4Ab @ jquery-2.2.4.min.js:4z @ jquery-2.2.4.min.js:4(anonymous function) @ jquery-2.2.4.min.js:4send @ jquery-2.2.4.min.js:4ajax @ jquery-2.2.4.min.js:4(anonymous function) @ jquery.struts2.min.js?s2j=4.0.1:21each @ jquery-2.2.4.min.js:2require @ jquery.struts2.min.js?s2j=4.0.1:21slider @ VM44:40bind @ jquery.struts2.min.js?s2j=4.0.1:30(anonymous function) @ logout:160i @ jquery-2.2.4.min.js:2fireWith @ jquery-2.2.4.min.js:2ready @ jquery-2.2.4.min.js:2J @ jquery-2.2.4.min.js:2
> 		VM47:1 Uncaught TypeError: Cannot set property 'keyCode' of undefined(…)(anonymous function) @ VM47:1a.ui.keyCode.BACKSPACE @ VM47:1(anonymous function) @ VM47:1globalEval @ jquery-2.2.4.min.js:2text script @ jquery-2.2.4.min.js:4Ab @ jquery-2.2.4.min.js:4z @ jquery-2.2.4.min.js:4(anonymous function) @ jquery-2.2.4.min.js:4send @ jquery-2.2.4.min.js:4ajax @ jquery-2.2.4.min.js:4(anonymous function) @ jquery.struts2.min.js?s2j=4.0.1:21each @ jquery-2.2.4.min.js:2require @ jquery.struts2.min.js?s2j=4.0.1:21slider @ VM44:40bind @ jquery.struts2.min.js?s2j=4.0.1:30(anonymous function) @ logout:160i @ jquery-2.2.4.min.js:2fireWith @ jquery-2.2.4.min.js:2ready @ jquery-2.2.4.min.js:2J @ jquery-2.2.4.min.js:2
> 		VM49:2 Uncaught TypeError: b is not a constructor(…)c.widget @ VM49:2(anonymous function) @ VM50:1(anonymous function) @ VM50:1(anonymous function) @ VM50:1globalEval @ jquery-2.2.4.min.js:2text script @ jquery-2.2.4.min.js:4Ab @ jquery-2.2.4.min.js:4z @ jquery-2.2.4.min.js:4(anonymous function) @ jquery-2.2.4.min.js:4send @ jquery-2.2.4.min.js:4ajax @ jquery-2.2.4.min.js:4(anonymous function) @ jquery.struts2.min.js?s2j=4.0.1:21each @ jquery-2.2.4.min.js:2require @ jquery.struts2.min.js?s2j=4.0.1:21slider @ VM44:40bind @ jquery.struts2.min.js?s2j=4.0.1:30(anonymous function) @ logout:160i @ jquery-2.2.4.min.js:2fireWith @ jquery-2.2.4.min.js:2ready @ jquery-2.2.4.min.js:2J @ jquery-2.2.4.min.js:2
> 		VM44:42 Uncaught TypeError: c.slider is not a function(…)

Latest snapshot working version: 4.0.1-20160922.161421-11, but I have just realized that version 4.0.1-SNAPSHOT was removed from snapshot's repository.

Thanks!

**Comment by sdutry** [comment]
created git repository that can simulate problem:
(created with the archetype and updated versions)

[https://github.com/sdutry/issue89](https://github.com/sdutry/issue89)

start with `mvn jetty:run`

then go to [http://localhost:8080/issue89/issue89.action](http://localhost:8080/issue89/issue89.action)

I'm not completely confident that it's not just a misconfiguration since the showcase site does work.
I'll investigate further.

**Comment by flofourcade** [comment]
Got the same issue with autocompleter. Seems like core.js (jquery ui) is not loaded. Using loadAtOnce=true in the head tag should fix the problem. Maybe the showcase is configured this way.

**Comment by sdutry** [comment]
@flofourcade loading too late of one of the libraries could be the problem

`Uncaught TypeError: $.ui.safeActiveElement is not a function(…)`

The fact that none of the specific items actualy get executed right away on the showcase might be the reason why it works.

doesn't look like the showcase is configured with the ´loadAtOnce=true´ attribute

```
    <s:if test="%{theme == 'showcase' || theme == null}">
        <sj:head debug="false" compressed="true" jquerytheme="showcase" customBasepath="themes" 
                 loadFromGoogle="%{google}" ajaxhistory="%{ajaxhistory}" defaultIndicator="myDefaultIndicator"
                 defaultLoadingText="Please wait ..."/>
    </s:if>
    <s:else>
        <sj:head debug="false" compressed="true" jquerytheme="%{theme}" loadFromGoogle="%{google}" 
                 ajaxhistory="%{ajaxhistory}" defaultIndicator="myDefaultIndicator"
                 defaultLoadingText="Please wait ..."/>
    </s:else>
```

**Comment by flofourcade** [comment]
Ok.Saw that head.ftl has been changed. I ll take a look tomorrow .

**Comment by sdutry** [comment]
@flofourcade 
for some reason loading jquery from google also fixes the problem:
`loadFromGoogle="true"`

**Comment by sdutry** [comment]
loaded from google:
``` 
    <script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.js"></script>
    <script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.js"></script>
<script type="text/javascript" src="/issue89/struts/js/plugins/jquery.form.js?s2j=4.0.2-SNAPSHOT"></script>
<script type="text/javascript" src="/issue89/struts/js/plugins/jquery.subscribe.js?s2j=4.0.2-SNAPSHOT"></script>

<script type="text/javascript" src="/issue89/struts/js/struts2/jquery.struts2.js?s2j=4.0.2-SNAPSHOT"></script>

<script type="text/javascript">
    $(function () {
        jQuery.struts2_jquery.version = "4.0.2-SNAPSHOT";
        jQuery.struts2_jquery.debug = true;
        jQuery.struts2_jquery.loadAtOnce = true;
        jQuery.scriptPath = "/issue89/struts/";
        jQuery.struts2_jquery.minSuffix = "";
        jQuery.ajaxSettings.traditional = true;

        jQuery.ajaxSetup({
            cache: false
        });

        jQuery.struts2_jquery.require("js/struts2/jquery.ui.struts2.js?s2j=4.0.2-SNAPSHOT");

    });
</script>

        <link id="jquery_theme_link" rel="stylesheet"
              href="//ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/start/jquery-ui.css" type="text/css"/>
```

not loaded from google

```
        <script type="text/javascript" src="/issue89/struts/js/base/jquery-2.2.4.js"></script>
        <!-- script type="text/javascript" src="/issue89/struts/js/base/core.js?s2j=4.0.2-SNAPSHOT"></script -->
<script type="text/javascript" src="/issue89/struts/js/plugins/jquery.subscribe.js?s2j=4.0.2-SNAPSHOT"></script>

<script type="text/javascript" src="/issue89/struts/js/struts2/jquery.struts2.js?s2j=4.0.2-SNAPSHOT"></script>

<script type="text/javascript">
    $(function () {
        jQuery.struts2_jquery.version = "4.0.2-SNAPSHOT";
        jQuery.struts2_jquery.debug = true;
        jQuery.scriptPath = "/issue89/struts/";
        jQuery.struts2_jquery.minSuffix = "";
        jQuery.ajaxSettings.traditional = true;

        jQuery.ajaxSetup({
            cache: false
        });

        jQuery.struts2_jquery.require("js/struts2/jquery.ui.struts2.js?s2j=4.0.2-SNAPSHOT");

    });
</script>

        <link id="jquery_theme_link" rel="stylesheet"
              href="/issue89/struts/themes/start/jquery-ui.css?s2j=4.0.2-SNAPSHOT"
              type="text/css"/>
```

so unless i'm mistaken, it's missing the following javascripts:
```
<script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.js"></script>
<script type="text/javascript" src="/issue89/struts/js/plugins/jquery.form.js?s2j=4.0.2-SNAPSHOT"></script>

```

**Comment by matorodriguez** [comment]
Great.
Note: when loading from Google, a HTTP NOT FOUND arises: 
http://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/i18n/datepicker-es.min.js

**Comment by sdutry** [comment]
further testing shows that without the `loadFromGoogle` or the `loadAtOnce` the `jquery-ui.js` file never gets loaded.

from google:
```
<#if parameters.loadFromGoogle?default(false)>
    <#if parameters.jquery?default(true)>
    <script type="text/javascript" src="${jqueryGoogle}"></script>
    </#if>
    <#if parameters.jqueryui?default(true)>
    <script type="text/javascript" src="${jqueryUiGoogle}"></script>
...
```

not from google:
```
<#else>
    <#if parameters.jquery?default(true)>
        <script type="text/javascript" src="${javaScriptBasePath}js/base/${jqueryFile}"></script>
    </#if>
    <#if parameters.jqueryui?default(true)>
        <#if parameters.loadAtOnce?default(false)>
        <script type="text/javascript" src="${javaScriptBasePath}js/base/${jqueryUIFile}"></script>
...
```

I think it might be nescessary to always load the `jquery-ui.js` immediately, even with the loadAtOnce to be false.
I can't realy find it being loaded through a `self.require` call anywhere else

**Comment by sdutry** [comment]
@matorodriguez it seems like the google urls don't contain the i18n folder with the different translations for version `1.12.1`, which this setup assumes.

It did for all previous versions, so the only current workaround option you have is to add `loadAtOnce="true"` (it does have the translation files packaged inside with the struts2-jquery-plugin)

**Comment by matorodriguez** [comment]
Great work @sdutry, thanks a lot!

**Comment by sdutry** [comment]
@jogep @flofourcade 
i made the following branch with what i think would fix this issue:
[issue89](https://github.com/sdutry/struts2-jquery/tree/issue89)

The problem i have is that the moment i made the branch off of `release/4.0.2` , my branch was already 2 commits ahead (and they're not mine).
So i'm not sure how to start a pull-request with only the changes i made.

**Comment by flofourcade** [comment]
The problem with always loading jquery-ui.js is that we loose the "lazy" loading of jquery-uis's component when loadAtOnce and loadFromGoogle are false. When false, the expected behaviour is that each widget use $.require to load each needed jquery-ui's component using the splitted version of jquery ui js (selectable.js, core.js, slider.js,...).

 Between the last snapshot and the release, this splitted version of jquery ui has changed (new unique-id.js, some functions have been moved to other file,...) . 

I think the only way to restore the expected behaviour of loadAtOnce="false" is to test every widget individually and to fix broken dependencies with $.require. 
By eg, the autocompleter tag uses $(..).uniqueId, previously declared in core.js, but now in it's own file unique-id.js, but autocompleter in jquery.ui.struts2.js has not been updated to load this new dependency ...

**Comment by sdutry** [comment]
@flofourcade 
Ok,

I can try to have a look at it this weekend, working my way through them one at a time.

ps: any idea how to get around the 2 commits ahead the moment i make a fork?

**Comment by flofourcade** [comment]
Sorry, I'm far to be a github's specialist ! Maybe is there a way to exclude some file when you'll create your PR ?

**Comment by lukaszlenart** [comment]
> ps: any idea how to get around the 2 commits ahead the moment i make a fork?

Use `origin` ;-)

The best option to prepare PRs is to clone the original repo locally, then make a fork on GitHub, add it as a `remote` to your cloned original repo

`git remote add fork git@....`

now when you're at `master` create a branch

`git checkout -b my-patch`

make changes and commit, now push to your `fork`

`git push -u fork my-patch`

go to GitHub and you will see that you can create a PR, open it and you're done :)

When your PR went in, update `master` from `origin` and drop the branch

```
git checkout master
git fetch -p
git pull
git branch -d my-patch
```

and you can start creating a new PR :)

**Comment by sdutry** [comment]
@lukaszlenart 
i did the following:

1. added a remote to the original repo ( `git remote add upstream <git repo>` )
2. created a branch out of the remote branch from the original repo ( `checkout -b <branchname>` )
3. push that to my fork of the repo ( `git push origin <branchname>`)
4. branch is 2 commits ahead of ...

So i don't know where those commits originate from

**Comment by sdutry** [comment]
@flofourcade 
I'd like you to check that what i'm doing is correct.
Currently fixed the sj:dialog by adding jquery-ui to the scripts to require. (since the problem there was that jquery.ui was undefined)

see [commit](https://github.com/sdutry/struts2-jquery/commit/03214c79f3ef4baf696da226848defe8e4197d10)

I'll continue going through the rest 1 by 1, i just wanted to know if i was heading the right way with this fix.

**Comment by flofourcade** [comment]
@sdutry 
You may try first first with core.js which contains main jquery ui functions/declarations for the splitted version of jquery ui for lazy loading. 
If you look at the current version of head.ftl, you'll see that the loading of core.js has been commented, but not added to the require directive of some widget that need it.
If you want i will make some test and tell you here.

**Comment by flofourcade** [comment]
@sdutry 
Making widget.js first in the require directive make the dialog working. No need to add core.js or jquery-ui.js !

**Comment by sdutry** [comment]
@flofourcade 
Ok, thx for the info.

I was still juggling with the javascripts to figure it out.

**Comment by flofourcade** [comment]
Ok, I've tested dialogs-*.jsp of the showcase in isolation (loading it without ajax and with a <sj:head> without loadAtOnce or loadByGoogle).
If widget.js is loaded first everything works.
dialog-modal.jsp is broken, seems there is a problem with opacity attributes, leading to incorrect JS generated by the tag. Removing them fix the problem.

**Comment by sdutry** [comment]
@flofourcade 

finaly found why it had to be first:

inside `mouse.js` (which was previously first) there is the following code:

`return $.widget( "ui.mouse", {`

**Comment by flofourcade** [comment]
The sad thing is that we have to test all tags in isolation, it's highly probable that other tags are impacted !

**Comment by sdutry** [comment]
i'll start by going around and fixing the location of widget.js wherever mouse.js is loaded.

**Comment by sdutry** [comment]
checked tags (against branch [issue89fix](https://github.com/sdutry/struts2-jquery/tree/issue89fix) )(will be updated):

- `sj:slider`

**Comment by sdutry** [comment]
@flofourcade 

seems that one of the main problems for some of the javascripts like 
- keycode.js
- safe-active-element.js

would be that they don't have `jQuery.ui` defined.

putting a javascript infront of them that has the following ui dummy definition if it doesn't exist, fixes it:
`$.ui = $.ui || {};`

maybe it would be a better idea to put the `version.js` inside the `head.ftl` ? 
(since all that does is setting the version of `jQuery.ui`)

or would it be an option to modify the files with the problems to add the code below to them?
`$.ui = $.ui || {};`

**Comment by flofourcade** [comment]
@sdutry
To fix autocompleter : 
jquery.ui.struts:.js line 866
```javascript
self.require([                	
                	"js/base/widget" + self.minSuffix + ".js",                                      
                    "js/base/version" + self.minSuffix + ".js",                   
                    "js/base/unique-id" + self.minSuffix + ".js",
                    "js/base/position" + self.minSuffix + ".js",
                    "js/base/menu" + self.minSuffix + ".js",
                    "js/base/keycode" + self.minSuffix + ".js",
                    "js/base/safe-active-element" + self.minSuffix + ".js",
                    "js/base/autocomplete" + self.minSuffix + ".js"
                ]);
```
and jquery.ui.struts:.js line 1050
```javascript
                    self.require([ "js/base/widget" + self.minSuffix + ".js", "js/base/button" + self.minSuffix + ".js", "js/base/tooltip" + self.minSuffix + ".js" ]);

```

Need to add unique-id.js and tooltip.js for combobox and to change depencies loading order.

**Comment by sdutry** [comment]
@flofourcade i just did that and commited it, although my ordering of requires is a bit different

**Comment by flofourcade** [comment]
Yes you're right for keycode and safe-active-element, got the same problem while trying to fix autocomplete. We can try your solution based on version.js I think it's a good way.

**Comment by sdutry** [comment]
@flofourcade 

which solution then?

1. adding `$.ui = $.ui || {};` in head.ftl
2. adding `version.js` in head.ftl
3. changing the javascripts that don't include the `$.ui = $.ui || {};` empty object creation if it doesn't exist

**Comment by flofourcade** [comment]
Add version.js to head.ftl. you can declare it in place of the commented declaration of core.js which is deprecated now. With this setup, version.js will be loaded when in lazy mode

**Comment by sdutry** [comment]
@flofourcade 
version.js added with this [commit](https://github.com/sdutry/struts2-jquery/commit/ddf9d048b303b1cbbed69e3b54e7820359b0ee81)

**Comment by sdutry** [comment]
additional problem:

`jquery.combobox.js` and `jquery.combobox.min.js` are out of sync, resulting in different classes being added to the autocompleter-selectbox.

(will fix shortly, just putting it here so i don't forget)

**Comment by sdutry** [comment]
checked tags (against branch [issue89fix](https://github.com/sdutry/struts2-jquery/tree/issue89fix) )(will be updated):
ok:
- `sj:accordion`
- `sj:autocompleter`
- `sjc:chart`
- `sjc:chartData`
- `sj:datepicker`
- `sj:slider`

broken:

(moved comment to the bottom to keep track of what's checked)

**Comment by lukaszlenart** [comment]
@sdutry no idea what's wrong, I'm always fetch & pull the original repo before creating a branch and it works like a charm.

**Comment by sdutry** [comment]
@flofourcade 

can you check something for me:

when trying to load the `datatables-group.action` seperately, the collapsing of the groups isn't working. 

the problem seems to be that the following javascript is executed before the table is loaded and thus doesn't get the chance to bind the click on the rows.

```
$('#groupTable tbody').on( 'click', 'tr.group', function () {
	var group = $(this).data("group");
	$(this).toggleClass("collapsed");
	$("tr.child-of-group-"+group).toggle();
});
```
placing those lines inside a document ready is what fixes it for me, but i'm not sure if it's something that should be addressed or if it's only a local problem for me. (or if this is the preferred workaround/solution)

**Comment by flofourcade** [comment]
Ok will have a look a this ASAP.

**Comment by sdutry** [comment]
checked tags (against branch [issue89fix](https://github.com/sdutry/struts2-jquery/tree/issue89fix) )(will be updated):
ok:
- `sj:accordion`
- `sj:autocompleter`
- `sjc:chart`
- `sjc:chartData`
- `sj:datepicker`
- `sj:dialog`
- `sjg:grid`
- `sjdt:datatables`
- `sj:slider`

broken:

(moved comment to the bottom to keep track of what's checked)

**Comment by sdutry** [comment]
@flofourcade @jogep 

Considering the branch i'm working on for this issue has a lot of changes already, i was thinking about making a pull request for what's fixed and moving the other remaining (mostly minor) problems into their own issues.

I'd like to hear your opinion on this. 
Also if:
- I overlooked an issue
- created a new problem
- you want me to check other tags/combinations

please let me know, so i could fix them before making the pull-request.

link to branch: [issue89fix](https://github.com/sdutry/struts2-jquery/tree/issue89fix)
