### ISSUE TITLE
version 4.0.1 in maven

### ISSUE THREAD

**Issue by afattahi54** [struts-community-plugins/struts2-jquery#91]
It seems that the version 4.0.1 is released, can we get it from any maven repository ?!

**Comment by sdutry** [comment]
It should be available from the default maven repositories

http://mvnrepository.com/artifact/com.jgeppert.struts2.jquery/struts2-jquery-plugin/4.0.1

**Comment by sdutry** [comment]
@afattahi54 

Did you manage to use version `4.0.1` ?

Please let us know so we can either
- help searching for a solution
- close the issue

**Comment by sdutry** [comment]
@afattahi54 

Version `4.0.2` has now been released with several bugfixes, please use this version instead.

[http://mvnrepository.com/artifact/com.jgeppert.struts2.jquery/struts2-jquery-plugin/4.0.2](http://mvnrepository.com/artifact/com.jgeppert.struts2.jquery/struts2-jquery-plugin/4.0.2)

```
<dependency>
    <groupId>com.jgeppert.struts2.jquery</groupId>
    <artifactId>struts2-jquery-plugin</artifactId>
    <version>4.0.2</version>
</dependency>
```
