### ISSUE TITLE
version 4.0.2 not yet showing up in central maven repository

### ISSUE THREAD

**Issue by sdutry** [struts-community-plugins/struts2-jquery#95]
@jogep 
Version `4.0.2` is not yet showing up in the maven repository.

I don't know what needs to be done for this.

- is there something extra that needs to be done?
- or is this just a normal delay?

the place where i was looking:
[mvnrepository](http://mvnrepository.com/artifact/com.jgeppert.struts2.jquery/struts2-jquery-plugin)

**Comment by jogep** [comment]
At least the version is available here:
https://oss.sonatype.org/content/groups/staging/com/jgeppert/struts2/jquery/struts2-jquery-plugin/

May it needs some time until it is synced with https://mvnrepository.com

**Comment by jogep** [comment]
https://mvnrepository.com/artifact/com.jgeppert.struts2.jquery/struts2-jquery-plugin/4.0.2
